version: '3'

services:
  server:
    build: 
      dockerfile: Dockerfile.dev 
      context: ./Backend
    ports:
      - '5000:5000'


  frontend:
    build:
      dockerfile: Dockerfile.dev 
      context: ./Frontend 
    volumes:
      - /app/node_modules
      - ./Frontend:/app 
    ports:
      - '8000:8000'