FROM python:3.9-slim

WORKDIR /app

COPY . .
RUN pip install --upgrade pip 
RUN pip install --no-cache-dir Flask
RUN pip install -r requirements.txt


CMD [ "flask", "--app", "server", "run", "--host=0.0.0.0", "--port", "5000"]
